API_V1_ROUTER_PREFIX = "/api/v1"

MAIN_ROUTER_PREFIX = ""
MAIN_ROOT = "/"

LOGIN_ROUTER_PREFIX = "/login"
LOGIN_ROOT = ""

LOGOUT_ROUTER_PREFIX = "/logout"
LOGOUT_ROOT = ""

USERS_ROUTER_PREFIX = "/users"
USERS_ROOT = ""
USERS_ID = "/{id}"

BOARDS_ROUTER_PREFIX = "/boards"
BOARDS_ROOT = ""
BOARDS_ID = "/{id}"

AIS_ROUTER_PREFIX = "/ais"
AIS_ROOT = ""
AIS_ID = "/{id}"

AILOGS_ROUTER_PREFIX = "/ailogs"
AILOGS_ROOT = ""
AILOGS_ID = "/{id}"
