API_V1_ROUTER_PREFIX = "/api/v1"

MAIN_ROUTER_PREFIX = ""
MAIN_ROOT = "/"

LOGIN_ROUTER_PREFIX = "/login"
LOGIN_ROOT = "/"

LOGOUT_ROUTER_PREFIX = "/logout"
LOGOUT_ROOT = "/"

JOIN_ROUTER_PREFIX = "/join"
JOIN_ROOT = "/"