ENDPOINT = ""
ENDPOINT_SLASH = "/"

API_V1_ROUTER_PREFIX = "/api/v1"

AUTH_ROUTER_PREFIX = "/auth"
AUTH_LOGIN_ROUTER_PREFIX = "/login"
AUTH_LOGOUT_ROUTER_PREFIX = "/logout"
AUTH_REISSUE_ACCESS_TOKEN_ROUTER_PREFIX = "/reissue-access-token"
AUTH_ISSUE_WEBSOCKET_ACCESS_TOKEN_ROUTER_PREFIX = "/issue-websocket-access-token"


MAIN_ROUTER_PREFIX = ""

USERS_ROUTER_PREFIX = "/users"
USERS_ID_ROUTER_PREFIX = "/{user_id}"

BOARDS_ROUTER_PREFIX = "/boards"
BOARDS_ID_ROUTER_PREFIX = "/{board_id}"

POSTS_ROUTER_PREFIX = "/posts"
POSTS_ID_ROUTER_PREFIX = "/{post_id}"

COMMENTS_ROUTER_PREFIX = "/comments"
COMMENTS_ID_ROUTER_PREFIX = "/{comment_id}"

AIS_ROUTER_PREFIX = "/ais"
AIS_ID_ROUTER_PREFIX = "/{ai_id}"

AILOGS_ROUTER_PREFIX = "/ailogs"
AILOGS_ID_ROUTER_PREFIX = "/{ailog_id}"

CHAT_SESSIONS_ROUTER_PREFIX = "/chat-sessions"
CHAT_SESSIONS_ID_ROUTER_PREFIX = "/{chat_session_id}"
CHAT_SESSIONS_ID_WEBSOCKET_PREFIX = "/ws"

CHATS_ROUTER_ROUTER_PREFIX = "/chats"
CHATS_ID_ROUTER_ROUTER_PREFIX = "/{chat_id}"
