version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - app-network
  app:
    # image: 사전 빌드한 이미지 혹은 허브 이미지
    build: .
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
    command: >
      /bin/bash -c "/code/app/app_init.sh"
    volumes:
      - ./volume/database/:/code/app/volume/database/
      - ./volume/ai_model_store/:/code/app/volume/ai_model_store/
      - ./volume/staticfile/:/code/app/volume/staticfile/
    networks:
      - app-network
  celery:
    # image: 사전 빌드한 이미지 혹은 허브 이미지
    build: .
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
    command: /bin/bash -c "celery -A celery_app worker -l info --pool=solo"
    volumes:
      - ./volume/database/:/code/app/volume/database/
      - ./volume/ai_model_store/:/code/app/volume/ai_model_store/
      - ./volume/staticfile/:/code/app/volume/staticfile/
    networks:
      - app-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
networks:
  app-network:
    driver: bridge