name: Update-README
on:
  push:
    branches:
      - main
jobs:
  update-readme:
    name: update README
    runs-on: ubuntu-latest

    steps:
    - name: Checkout my repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11.5
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.5"
        
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install anytree
        pip install starlette
        pip install SQLAlchemy
        pip install pydantic_settings
        pip install fastapi
        
    - name: Update README.md
      run: |
        README_ORIGIN_PATH=./readme_format/README.md
        README_TARGET_PATH=./README.md
        cp $README_ORIGIN_PATH $README_TARGET_PATH
        ENV_ORIGIN_PATH=./app/.env-example
        ENV_TARGET_PATH=./github_actions_py/.env
        cp $ENV_ORIGIN_PATH $ENV_TARGET_PATH
        cd github_actions_py
        python update_readme_project_directory_tree.py
        python update_readme_project_model.py

    - name: Commit and push Updated README.md
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add README.md
        git commit -m "[Docs] Update README.md"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
        
